3 flex
anshamr1/dz-html-css pull request #2
Opened 2024-08-27 22:40 UTC by anshamr1

2024-08-27 22:44 UTC, anshamr1 commented
Не получилось сделать в ДЗ 17.17 :
1. Поле "Зарегистрироваться" съехало, не смог выровнять
2. Не смог наложить img стрелку
3. Не смог сделать background-color gradient

2024-09-03 09:39 UTC, GitEsense requested changes
Посмотрите комментарии.
Повторите информацию про флекс - бокс, про блочную модель (как именно ведут себя блоки), так же в упражнениях шла речь и про "wrapper" (обёртку), повторите позиционирование (абсолютное и relative, почему так), посмотрите и в сторону transform - почитайте о нём, если у Вас нет понимания, лучше "повторить" и прям "пощупать", т.е. возьмите какой-нибудь пример и попробуйте "расписать" для себя как это должно выглядеть, затем посмотрите код и сравните (плюс минус блочное выделение будет идентично, вопрос лишь кол-ва обёрток)

2024-09-03 09:39 UTC, GitEsense commented on 1-Blog/index.html
>          </div>
У Вас тут проблема с позиционированием, потому что Вы пытаетесь выстроить три элемента вместо двух, сделайте для текста один блок (div для двух параграфов), тогда у Вас будет 2 элемента
1. картинка (аватар)
2. блок с параграфами

тогда обычный flex сделает "в строку", тем самым останется отцентровать и дать "gap"

2024-09-03 09:39 UTC, GitEsense commented on 2-Form/styles.css
> +}
Вы указали позишн, но не указали "его местоположение", т.е. top / bottom / left / right
Так же не указали и относительно "кого", т.е. position relative на нужного родителя

Вложите картинку внутрь кнопки, сделайте кнопку position relative, укажите картинке положение "справа = 0, сверху 50%", затем, чтобы "вычесть" размер иконки (и компенсировать сдвиг) можно указать transform: translate(-50%, -50%), что тут происходит? мы трансформируем элемент, делаем "сдвиг" на 50% назад от его ширины по оси X и на 50% "назад" от его высоты по оси Y

2024-09-03 09:39 UTC, GitEsense commented on 2-Form/styles.css
> +    padding 9px 102px;
размеры лучше указывать "max-width" или в процентах, так не будет "проблемы" при "масштабировании"

2024-09-03 10:16 UTC, anshamr1 commented on 1-Blog/index.html
>          </div>
Спасибо, получилось. Не знаю, почему раньше об этом не подумал.  Понял, что правильная верстка не меньше важна, чем применение правильных стилей.

2024-09-04 14:38 UTC, GitEsense requested changes
Для "примера" оставлю Вам готовую форму, с целью, чтобы Вы проанализировали код и реализовали "Блог" без сучка и задоринки по "примеру" и "подобию"

**HTML**
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Домашнее задание №1 (Вёрстка)" />
        <link rel="stylesheet" href="./styles/style.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet" />
        <title>2-Form</title>
    </head>
    <body>
        <main>
            <form action="">
                <div class="title">
                    <h1>Регистрация</h1>
                    <p>
                        Уже есть аккаунт?
                        <a href="#">Войти</a>
                    </p>
                </div>
                <input type="text" name="company" placeholder="Компания" value="Моя компания" />
                <div class="field">
                    <input type="text" name="firstname" placeholder="Имя" />
                    <input type="text" name="surname" placeholder="Фамилия" />
                </div>
                <input type="email" name="email" placeholder="E-mail" />
                <button type="submit">Зарегистрироваться</button>
                <div class="policy">
                    <input type="checkbox" name="checkbox" id="checkbox" />
                    <label for="checkbox">Я прочитал и принимаю <a href="#">Условия пользования</a></label>
                </div>
            </form>
        </main>
    </body>
</html>
```

**А вот и CSS**
```css
* {
    box-sizing: border-box;
}
html {
    background: linear-gradient(225deg, #fdc5c5 25.45%, rgba(242, 152, 222, 0) 100%),
        linear-gradient(225deg, #ffa5a5 33.09%, rgba(255, 255, 255, 0) 82.34%), #f39494;
    height: 100%;
}
body {
    margin: 0;
    font-family: 'Open Sans', sans-serif;
}
main {
    max-width: 1440px;
    margin: 0 auto;
}
form {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    max-width: 582px;
    border-radius: 10px;
    padding: 72px 94px 91px;
    background-color: #fffefe;
    box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);

    /* flex */
    display: flex;
    flex-flow: column wrap;
    justify-content: center;
    align-items: center;
    gap: 22px 1px;
}

h1 {
    color: #333;
    font-size: 36px;
    line-height: 54px;
    margin: 0;
}
p {
    color: #666;
    font-size: 18px;
    margin: 0;
}
a {
    color: #089fe0;
    font-size: 14px;
    text-decoration: none;
}
label {
    color: #666;
    font-size: 14px;
}
span {
    font-size: 14px;
}
input:not([type="checkbox"]) {
    color: #999;
    background-color: #f5f5f5;
    font-size: 16px;
    font-style: italic;
    border: 0;
    border-radius: 5px;
    width: 100%;
    line-height: 26px;
    border: 1px solid #f5f5f5;
    padding: 9px 35px 9px 11px;
}
button {
    padding: 9px 12px;
    width: 100%;
    border: 0;
    border-radius: 5px;
    font-size: 18px;
    color: #fff;
    background: url('../images/arrow.svg') no-repeat right 24px center #089fe0;
}

input:not([type="checkbox"]):focus {
    background-color: #fff;
    color: #333;
    font-style: normal;
    font-weight: 600;
}
.policy {
    align-self: flex-start;
    position: relative;
}
.policy input {
    width: auto;
}
.field {
    display: flex;
    gap: 1px;
}

.field input:first-child {
    border-radius: 5px 0 0 5px;
}
.field input:last-child {
    border-radius: 0 5px 5px 0;
}

.title {
    margin-bottom: 25px;
}
.title a {
    font-size: 18px;
    text-decoration: underline;
}
input[type='checkbox'] {
    opacity: 0;
}
input[type='checkbox']:checked + label[for='checkbox']::before {
    background-color: #089fe0;
    content: '✖';
    padding: 0 3px;
    color: white;
}
label[for='checkbox']::before {
    content: ' ';
    position: absolute;
    top: 0;
    left: 0;
    display: inline-block;
    margin: 2px;
    padding: 7px;
    border-radius: 5px;
    border: 1px solid #eeeeee;
    background-color: #f5f5f5;
    font-size: 11px;
}
```

2024-09-04 14:38 UTC, GitEsense commented on 1-Blog/styles/style.css
> +    margin: 0 457px 30px 457px;
Вот таких margin'ов быть не должно, т.к. размер экрана у нас может быть и меньше, и больше, позиционируем "слева и справа" мы "автоматически", следовательно будет margin: 0 auto 30px, где 0 для top, auto для left/right и 30px для bottom

2024-09-04 14:38 UTC, GitEsense commented on 1-Blog/styles/style.css
> +}
Это у нас единичный span - зачем там флекс? margin так же не нужен, мы можем "на лого" повесить align-items: center, flex, gap и получим "структуру", вместо "корневого" параграфа использовать обычную ссылку, в которой вложен span (icon) и рядом "текст", тоже можно в span / p

2024-09-04 14:38 UTC, GitEsense commented on 1-Blog/styles/style.css
> +}
Мы можем вообще сделать всё очень красиво, завернув несколько "оптимизашек", например
```css
header, main {
    margin: 0 auto;
    max-width: 1080px;
}

header {
    padding: 71px 0 69px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 77px;
}
nav {
    flex: 1;
}

nav ul {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    align-items: center;
    gap: 39px;
}

nav ul li:first-child{
    margin-right: 13px;
}
```

для лого
```html
<a href="#" class="blog">
        <span class="blogIcon">В</span>
        <span class="bloglink">Мой блог</span>
</a>
```

И продолжая в том же духе. Посмотрите на предложенную реализую, посмотрите на Ваш код и попробуйте придумать "оптимизашки", с правильным расположением

2024-09-13 15:41 UTC, GitEsense approved these changes

2024-11-30 12:58 UTC, merged